name: bond
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  ### Common Package
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  loading_animation_widget: ^1.3.0
  collection: ^1.19.1
  flutter_cache_manager: ^3.4.1
  flutter_secure_storage: ^10.0.0-beta.5
  sidebarx: ^0.17.2

  permission_handler: ^12.0.1
  logger: ^2.6.2
  uuid: ^4.5.2
  flutter_gen: ^5.12.0

  ### Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  ### Firebase
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_auth: ^6.1.2
  sign_in_with_apple: ^8.0.0-spm.1
  google_sign_in: ^7.2.0
  firebase_crashlytics: ^5.0.5
  firebase_analytics: ^12.0.4

  ### Networking
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  jwt_decoder: ^2.0.1
  app_links: ^7.0.0
  socket_io_client: ^3.1.3


  ### Location
  location: ^8.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  open_settings_plus: ^0.4.0


  ### Media
  flutter_blurhash: ^0.9.1
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.2.3

  ### Ui Design
  another_flushbar: ^1.12.32
  flutter_native_splash: ^2.4.7
  flutter_animate: ^4.5.2
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  fluttertoast: ^9.0.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  package_info_plus: ^9.0.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  infinite_scroll_pagination: ^5.1.1
  share_plus: ^12.0.1
  modal_bottom_sheet: ^3.0.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_screenutil: ^5.9.3
  syncfusion_flutter_pdfviewer: ^32.1.23
  webview_flutter: ^4.13.1
  chips_choice: ^3.0.1

  ### State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0


  ### clean architecture
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it:
  flutter_dotenv: ^6.0.0
  injectable: ^2.7.1

  ### Routing
  auto_route: ^11.1.0
  like_button: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.4.0
  flutter_gen_runner: ^5.12.0
  auto_route_generator: ^10.4.0


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/gif/
    - .env.production


  fonts:
    - family: GE
      fonts:
        - asset: assets/fonts/ge_ss/GE_SS_Two_Bold.otf
          weight: 700
        - asset: assets/fonts/ge_ss/GE_SS_Two_Medium.otf
          weight: 500
        - asset: assets/fonts/ge_ss/GE_SS_Two_Light.otf
          weight: 300

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200

flutter_intl:
  enabled: true
